- name: create cart
  hosts: cart
  become: yes
  tasks:

    - name: enable nodejs 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install node js
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Add cart
      ansible.builtin.user:
        name: roboshop
        system: true
        shell: /sbin/nologin
        home: /app
        comment: "roboshop system cart"

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app
        state: directory


    - name: delete cart zip file
      ansible.builtin.file:
          path: /tmp/cart.zip
          state: absent      

    - name: Download catatlogue.zip
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
        dest: /tmp/cart.zip

     

    - name: Extract cart.zip
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app 
        remote_src: yes

    - name: Install packages based on package.json.
      community.general.npm:
        path: /app

    - name: copy service
      ansible.builtin.template:
       src: cart.service
       dest: /etc/systemd/system/cart.service

    - name: daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start cart
      ansible.builtin.service:
        name: cart
        daemon-reload: true
        state: restarted
        enabled: yes      