- name: create rabbitmq
  hosts: rabbitmq
  become: yes
  tasks:

    - name: enable rabbitmq
      ansible.builtin.dnf:
        name: rabbitmq-server
        state: present

    - name: restart service
      ansible.builtin.systemd_service:
        name: rabbitmq-server
        state: started
        enabled: true  
        
    - name: create rabbitmq user
      community.rabbitmq.rabbitmq_user:
        user: roboshop 
        password: roboshop123
        permissions:
          - vhost: /
            configure_priv: .*
            read_priv: .*
            write_priv: .*
        state: present       